insert into AssetDetails (id, assetAssociation, columnName, value) values (1, 1, 'Ip Address', '177.174.108.119');
insert into AssetDetails (id, assetAssociation, columnName, value) values (2, 2, 'Location', 'Strongsville');
insert into AssetDetails (id, assetAssociation, columnName, value) values (3, 3, 'Location', 'Barberton');
insert into AssetDetails (id, assetAssociation, columnName, value) values (4, 4, 'Ip Address', '24.92.70.228');
insert into AssetDetails (id, assetAssociation, columnName, value) values (5, 5, 'Ip Address', '185.117.151.248');
insert into AssetDetails (id, assetAssociation, columnName, value) values (6, 6, 'Ip Address', '13.8.62.56');
insert into AssetDetails (id, assetAssociation, columnName, value) values (7, 7, 'Ip Address', '242.175.199.207');
insert into AssetDetails (id, assetAssociation, columnName, value) values (8, 8, 'Location', 'Lakeview');
insert into AssetDetails (id, assetAssociation, columnName, value) values (9, 9, 'Ip Address', '1.208.161.212');
insert into AssetDetails (id, assetAssociation, columnName, value) values (10, 10, 'Location', 'Akron');
