insert into Assets (id, name, icon, userRelation) values (1, 'Corolla', 1, 1);
insert into Assets (id, name, icon, userRelation) values (2, 'Mustang', 2, null);
insert into Assets (id, name, icon, userRelation) values (3, 'Corvette', 3, 3);
insert into Assets (id, name, icon, userRelation) values (4, 'Protege', 4, null);
insert into Assets (id, name, icon, userRelation) values (5, 'LTD Crown Victoria', 5, null);
insert into Assets (id, name, icon, userRelation) values (6, 'IS-F', 6, null);
insert into Assets (id, name, icon, userRelation) values (7, 'Murano', 7, null);
insert into Assets (id, name, icon, userRelation) values (8, 'Odyssey', 8, 8);
insert into Assets (id, name, icon, userRelation) values (9, 'Contour', 5, 9);
insert into Assets (id, name, icon, userRelation) values (10, 'Mirage', 2, null);
